apiVersion: v1
kind: Service
metadata:
  name: monolithic
  namespace: default
  labels:
    app: monolithic
spec:
  selector:
    app: monolithic
  type: NodePort
  ports:
  - name: http
    port: 8080
